import { Manrope } from "next/font/google";
import "@/_styles/globals.css";
import { Header } from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata = {
  title: "NetPhonix",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${manrope.className} bg-[#050505]`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
