export const mygenres = [
  { id: "hanh-dong", name: "Hành Động" },
  { id: "phieu-luu", name: "Phiêu Lưu" },
  { id: "hoat-hinh", name: "Hoạt Hình" },
  { id: "hai", name: "Hài" },
  { id: "hinh-su", name: "Hình Sự" },
  { id: "tai-lieu", name: "Tài Liệu" },
  { id: "chinh-kich", name: "Chính Kịch" },
  { id: "gia-dinh", name: "Gia Đình" },
  { id: "gia-tuong", name: "Giả Tưởng" },
  { id: "lich-su", name: "Lịch Sử" },
  { id: "kinh-di", name: "Kinh Dị" },
  { id: "nhac", name: "Nhạc" },
  { id: "bi-an", name: "Bí Ẩn" },
  { id: "lang-man", name: "Lãng Mạn" },
  { id: "khoa-hoc-vien-tuong", name: "Khoa Học Viễn Tưởng" },
  { id: "gay-can", name: "Gây Cấn" },
  { id: "chien-tranh", name: "Chiến Tranh" },
  { id: "tam-ly", name: "Tâm Lý" },
  { id: "tinh-cam", name: "Tình Cảm" },
  { id: "co-trang", name: "Cổ Trang" },
  { id: "mien-tay", name: "Miền Tây" },
  { id: "phim-18", name: "Phim 18+" },
];

export const mycountry = [
  { id: "au-my", name: "Âu Mỹ" },
  { id: "anh", name: "Anh" },
  { id: "trung-quoc", name: "Trung Quốc" },
  { id: "indonesia", name: "Indonesia" },
  { id: "viet-nam", name: "Việt Nam" },
  { id: "phap", name: "Pháp" },
  { id: "hong-kong", name: "Hồng Kông" },
  { id: "han-quoc", name: "Hàn Quốc" },
  { id: "nhat-ban", name: "Nhật Bản" },
  { id: "thai-lan", name: "Thái Lan" },
  { id: "dai-loan", name: "Đài Loan" },
  { id: "nga", name: "Nga" },
  { id: "ha-lan", name: "Hà Lan" },
  { id: "philippines", name: "Philippines" },
  { id: "an-do", name: "Ấn Độ" },
  { id: "quoc-gia-khac", name: "Quốc gia khác" },
];